buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
   command: npm install
   requiredFiles:
     - package.json
     - package-lock.json
     - .npmrc

livePreviewConfiguration:
  serveCommand: "npm run dev -- --port 8080"

dynamicRedirects:
  - from: */edit
    to: /puck
    status: 200